# Generated by Django 5.2.8 on 2025-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_data',
            name='emp_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_data',
            name='emp_role',
            field=models.CharField(max_length=100),
        ),
    ]
